@rem 复制到下载目录
copy @RootDirectory\bin\DotNet4.0\AgileIM.Client.exe @RootDirectory\appserver\xclient\files\AgileIM.Client.exe /y
copy @RootDirectory\bin\DotNet4.0\AgileIM.Client.exe.config @RootDirectory\appserver\xclient\files\AgileIM.Client.exe.config /y
copy @RootDirectory\bin\DotNet4.0\EAS.Communications.dll @RootDirectory\appserver\xclient\files\EAS.Communications.dll /y
copy @RootDirectory\bin\DotNet4.0\AxInterop.grdes6Lib.dll @RootDirectory\appserver\xclient\files\AxInterop.grdes6Lib.dll /y
copy @RootDirectory\bin\DotNet4.0\AxInterop.grpro6Lib.dll @RootDirectory\appserver\xclient\files\AxInterop.grpro6Lib.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.ActiveXForm.ClientClasp.AddIn.dll @RootDirectory\appserver\xclient\files\EAS.ActiveXForm.ClientClasp.AddIn.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.BPM.Activities.dll @RootDirectory\appserver\xclient\files\EAS.BPM.Activities.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.BPM.BLL.Host.dll @RootDirectory\appserver\xclient\files\EAS.BPM.BLL.Host.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.BPM.WinUI.dll @RootDirectory\appserver\xclient\files\EAS.BPM.WinUI.dll /y
copy @RootDirectory\bin\DotNet4.0\eas.client.ini @RootDirectory\appserver\xclient\files\eas.client.ini /y
copy @RootDirectory\bin\DotNet4.0\EAS.Configure.exe @RootDirectory\appserver\xclient\files\EAS.Configure.exe /y
copy @RootDirectory\bin\DotNet4.0\EAS.Configure.exe.config @RootDirectory\appserver\xclient\files\EAS.Configure.exe.config /y
copy @RootDirectory\bin\DotNet4.0\EAS.Data.Controls.dll @RootDirectory\appserver\xclient\files\EAS.Data.Controls.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.LuaScript.dll @RootDirectory\appserver\xclient\files\EAS.LuaScript.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Metadata.dll @RootDirectory\appserver\xclient\files\EAS.Metadata.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Data.dll @RootDirectory\appserver\xclient\files\EAS.Data.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Data.Provider.dll @RootDirectory\appserver\xclient\files\EAS.Data.Provider.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Distributed.dll @RootDirectory\appserver\xclient\files\EAS.Distributed.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Explorer.BLL.Contracts.dll @RootDirectory\appserver\xclient\files\EAS.Explorer.BLL.Contracts.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Explorer.BLL.Host.dll @RootDirectory\appserver\xclient\files\EAS.Explorer.BLL.Host.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Explorer.dll @RootDirectory\appserver\xclient\files\EAS.Explorer.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Explorer.Entities.dll @RootDirectory\appserver\xclient\files\EAS.Explorer.Entities.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Explorer.Res.dll @RootDirectory\appserver\xclient\files\EAS.Explorer.Res.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Explorer.WinUI.dll @RootDirectory\appserver\xclient\files\EAS.Explorer.WinUI.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.FormDesigner.exe @RootDirectory\appserver\xclient\files\EAS.FormDesigner.exe /y
copy @RootDirectory\bin\DotNet4.0\EAS.GReport.Controls.dll @RootDirectory\appserver\xclient\files\EAS.GReport.Controls.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.MicroKernel.dll @RootDirectory\appserver\xclient\files\EAS.MicroKernel.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Monitor.dll @RootDirectory\appserver\xclient\files\EAS.Monitor.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.NLB.Monitor.exe @RootDirectory\appserver\xclient\files\EAS.NLB.Monitor.exe /y
copy @RootDirectory\bin\DotNet4.0\EAS.NLB.Server.exe @RootDirectory\appserver\xclient\files\EAS.NLB.Server.exe /y
copy @RootDirectory\bin\DotNet4.0\EAS.MetaModeling.dll @RootDirectory\appserver\xclient\files\EAS.MetaModeling.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.MetaDesigner.exe @RootDirectory\appserver\xclient\files\EAS.MetaDesigner.exe /y
copy @RootDirectory\bin\DotNet4.0\EAS.MetaDesigner.exe.config @RootDirectory\appserver\xclient\files\EAS.MetaDesigner.exe.config /y
copy @RootDirectory\bin\DotNet4.0\EAS.Report.Controls.dll @RootDirectory\appserver\xclient\files\EAS.Report.Controls.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.SmartUpdater.exe @RootDirectory\appserver\xclient\files\EAS.SmartUpdater.exe /y
copy @RootDirectory\bin\DotNet4.0\EAS.SOA.Monitor.exe @RootDirectory\appserver\xclient\files\EAS.SOA.Monitor.exe /y
copy @RootDirectory\bin\DotNet4.0\EAS.ThirdParty.Controls.dll @RootDirectory\appserver\xclient\files\EAS.ThirdParty.Controls.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.WinClient.dll @RootDirectory\appserver\xclient\files\EAS.WinClient.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.WinClient.Start.exe @RootDirectory\appserver\xclient\files\EAS.WinClient.Start.exe /y
copy @RootDirectory\bin\DotNet4.0\EAS.WinClient.Start.exe.config @RootDirectory\appserver\xclient\files\EAS.WinClient.Start.exe.config /y
copy @RootDirectory\bin\DotNet4.0\EAS.Windows.dll @RootDirectory\appserver\xclient\files\EAS.Windows.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Wpf.Controls.dll @RootDirectory\appserver\xclient\files\EAS.Wpf.Controls.dll /y
copy @RootDirectory\bin\DotNet4.0\grdes6.dll @RootDirectory\appserver\xclient\files\grdes6.dll /y
copy @RootDirectory\bin\DotNet4.0\gregn6.dll @RootDirectory\appserver\xclient\files\gregn6.dll /y
copy @RootDirectory\bin\DotNet4.0\ICSharpCode.AvalonEdit.dll @RootDirectory\appserver\xclient\files\ICSharpCode.AvalonEdit.dll /y
copy @RootDirectory\bin\DotNet4.0\Interop.grdes6Lib.dll @RootDirectory\appserver\xclient\files\Interop.grdes6Lib.dll /y
copy @RootDirectory\bin\DotNet4.0\Interop.grpro6Lib.dll @RootDirectory\appserver\xclient\files\Interop.grpro6Lib.dll /y
copy @RootDirectory\bin\DotNet4.0\itextsharp.dll @RootDirectory\appserver\xclient\files\itextsharp.dll /y
copy @RootDirectory\bin\DotNet4.0\lua51.x64.dll @RootDirectory\appserver\xclient\files\lua51.x64.dll /y
copy @RootDirectory\bin\DotNet4.0\lua51.x86.dll @RootDirectory\appserver\xclient\files\lua51.x86.dll /y
copy @RootDirectory\bin\DotNet4.0\LuaInterface.x64.dll @RootDirectory\appserver\xclient\files\LuaInterface.x64.dll /y
copy @RootDirectory\bin\DotNet4.0\LuaInterface.x86.dll @RootDirectory\appserver\xclient\files\LuaInterface.x86.dll /y
copy @RootDirectory\bin\DotNet4.0\Microsoft.Data.ConnectionUI.Dialog.dll @RootDirectory\appserver\xclient\files\Microsoft.Data.ConnectionUI.Dialog.dll /y
copy @RootDirectory\bin\DotNet4.0\Microsoft.Data.ConnectionUI.dll @RootDirectory\appserver\xclient\files\Microsoft.Data.ConnectionUI.dll /y
copy @RootDirectory\bin\DotNet4.0\Microsoft.XmlNotepad.dll @RootDirectory\appserver\xclient\files\Microsoft.XmlNotepad.dll /y
copy @RootDirectory\bin\DotNet4.0\MongoDB.Bson.dll @RootDirectory\appserver\xclient\files\MongoDB.Bson.dll /y
copy @RootDirectory\bin\DotNet4.0\MongoDB.Driver.dll @RootDirectory\appserver\xclient\files\MongoDB.Driver.dll /y
copy @RootDirectory\bin\DotNet4.0\SequoiaDB.Bson.dll @RootDirectory\appserver\xclient\files\SequoiaDB.Bson.dll /y
copy @RootDirectory\bin\DotNet4.0\SequoiaDB.Driver.dll @RootDirectory\appserver\xclient\files\SequoiaDB.Driver.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Data.NoSQL.dll @RootDirectory\appserver\xclient\files\EAS.Data.NoSQL.dll /y
copy @RootDirectory\bin\DotNet4.0\MySql.Data.dll @RootDirectory\appserver\xclient\files\MySql.Data.dll /y
copy @RootDirectory\bin\DotNet4.0\RdlDesigner.dll @RootDirectory\appserver\xclient\files\RdlDesigner.dll /y
copy @RootDirectory\bin\DotNet4.0\RdlEngine.dll @RootDirectory\appserver\xclient\files\RdlEngine.dll /y
copy @RootDirectory\bin\DotNet4.0\RdlViewer.dll @RootDirectory\appserver\xclient\files\RdlViewer.dll /y
copy @RootDirectory\bin\DotNet4.0\System.Data.SQLite.DLL @RootDirectory\appserver\xclient\files\System.Data.SQLite.DLL /y
copy @RootDirectory\bin\DotNet4.0\System.Workflow.Activities.dll @RootDirectory\appserver\xclient\files\System.Workflow.Activities.dll /y
copy @RootDirectory\bin\DotNet4.0\System.Workflow.ComponentModel.dll @RootDirectory\appserver\xclient\files\System.Workflow.ComponentModel.dll /y
copy @RootDirectory\bin\DotNet4.0\System.Workflow.Runtime.dll @RootDirectory\appserver\xclient\files\System.Workflow.Runtime.dll /y
copy @RootDirectory\bin\DotNet4.0\update.ini @RootDirectory\appserver\xclient\files\update.ini /y
copy @RootDirectory\bin\DotNet4.0\WF.Demo.DAL.dll @RootDirectory\appserver\xclient\files\WF.Demo.DAL.dll /y
copy @RootDirectory\bin\DotNet4.0\WF.Demo.UI.dll @RootDirectory\appserver\xclient\files\WF.Demo.UI.dll /y

@rem 复制到下载配置目录
copy @RootDirectory\bin\DotNet4.0\EAS.SmartUpdateConfig.exe @RootDirectory\appserver\xclient\EAS.SmartUpdateConfig.exe /y
copy @RootDirectory\bin\DotNet4.0\EAS.SmartUpdateConfig.exe.config @RootDirectory\appserver\xclient\EAS.SmartUpdateConfig.exe.config /y

@rem 复制到SOA服务Bin目录
copy @RootDirectory\bin\DotNet4.0\EAS.SOA.BootStrap.dll @RootDirectory\appserver\bin\EAS.SOA.BootStrap.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Communications.dll @RootDirectory\appserver\bin\EAS.Communications.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.BPM.Activities.dll @RootDirectory\appserver\bin\EAS.BPM.Activities.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.BPM.BLL.Host.dll @RootDirectory\appserver\bin\EAS.BPM.BLL.Host.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Configure.exe @RootDirectory\appserver\bin\EAS.Configure.exe /y
copy @RootDirectory\bin\DotNet4.0\EAS.Configure.exe.config @RootDirectory\appserver\bin\EAS.Configure.exe.config /y
copy @RootDirectory\bin\DotNet4.0\EAS.LuaScript.dll @RootDirectory\appserver\bin\EAS.LuaScript.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Metadata.dll @RootDirectory\appserver\bin\EAS.Metadata.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Data.dll @RootDirectory\appserver\bin\EAS.Data.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Data.Provider.dll @RootDirectory\appserver\bin\EAS.Data.Provider.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Data.xml @RootDirectory\appserver\bin\EAS.Data.xml /y
copy @RootDirectory\bin\DotNet4.0\EAS.DbInitializer.exe @RootDirectory\appserver\bin\EAS.DbInitializer.exe /y
copy @RootDirectory\bin\DotNet4.0\EAS.DbInitializer.exe.config @RootDirectory\appserver\bin\EAS.DbInitializer.exe.config /y
copy @RootDirectory\bin\DotNet4.0\EAS.Distributed.dll @RootDirectory\appserver\bin\EAS.Distributed.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Explorer.BLL.Contracts.dll @RootDirectory\appserver\bin\EAS.Explorer.BLL.Contracts.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Explorer.BLL.Host.dll @RootDirectory\appserver\bin\EAS.Explorer.BLL.Host.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Explorer.dll @RootDirectory\appserver\bin\EAS.Explorer.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Explorer.Entities.dll @RootDirectory\appserver\bin\EAS.Explorer.Entities.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.MicroKernel.dll @RootDirectory\appserver\bin\EAS.MicroKernel.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Monitor.dll @RootDirectory\appserver\bin\EAS.Monitor.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.NLB.Monitor.exe @RootDirectory\appserver\bin\EAS.NLB.Monitor.exe /y
copy @RootDirectory\bin\DotNet4.0\EAS.NLB.Server.exe @RootDirectory\appserver\bin\EAS.NLB.Server.exe /y
copy @RootDirectory\bin\DotNet4.0\EAS.NLB.Server.exe.config @RootDirectory\appserver\bin\EAS.NLB.Server.exe.config /y
copy @RootDirectory\bin\DotNet4.0\EAS.NLB.Server.x64.exe @RootDirectory\appserver\bin\EAS.NLB.Server.x64.exe /y
copy @RootDirectory\bin\DotNet4.0\EAS.SOA.Server.exe @RootDirectory\appserver\bin\EAS.SOA.Server.exe /y
copy @RootDirectory\bin\DotNet4.0\EAS.SOA.Server.exe.config @RootDirectory\appserver\bin\EAS.SOA.Server.exe.config /y
copy @RootDirectory\bin\DotNet4.0\EAS.SOA.Server.x64.exe @RootDirectory\appserver\bin\EAS.SOA.Server.x64.exe /y
copy @RootDirectory\bin\DotNet4.0\EAS.SOA.Server.x64.exe.config @RootDirectory\appserver\bin\EAS.SOA.Server.x64.exe.config /y
copy @RootDirectory\bin\DotNet4.0\lua51.x64.dll @RootDirectory\appserver\bin\lua51.x64.dll /y
copy @RootDirectory\bin\DotNet4.0\lua51.x86.dll @RootDirectory\appserver\bin\lua51.x86.dll /y
copy @RootDirectory\bin\DotNet4.0\LuaInterface.x64.dll @RootDirectory\appserver\bin\LuaInterface.x64.dll /y
copy @RootDirectory\bin\DotNet4.0\LuaInterface.x86.dll @RootDirectory\appserver\bin\LuaInterface.x86.dll /y
copy @RootDirectory\bin\DotNet4.0\MongoDB.Bson.dll @RootDirectory\appserver\bin\MongoDB.Bson.dll /y
copy @RootDirectory\bin\DotNet4.0\MongoDB.Driver.dll @RootDirectory\appserver\bin\MongoDB.Driver.dll /y
copy @RootDirectory\bin\DotNet4.0\SequoiaDB.Bson.dll @RootDirectory\appserver\bin\SequoiaDB.Bson.dll /y
copy @RootDirectory\bin\DotNet4.0\SequoiaDB.Driver.dll @RootDirectory\appserver\bin\SequoiaDB.Driver.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Data.NoSQL.dll @RootDirectory\appserver\bin\EAS.Data.NoSQL.dll /y
copy @RootDirectory\bin\DotNet4.0\MySql.Data.dll @RootDirectory\appserver\bin\MySql.Data.dll /y
copy @RootDirectory\bin\DotNet4.0\RdlEngine.dll @RootDirectory\appserver\bin\RdlEngine.dll /y
copy @RootDirectory\bin\DotNet4.0\RdlViewer.dll @RootDirectory\appserver\bin\RdlViewer.dll /y
copy @RootDirectory\bin\DotNet4.0\soaserver.start.bat @RootDirectory\appserver\bin\soaserver.start.bat /y
copy @RootDirectory\bin\DotNet4.0\install.bat @RootDirectory\appserver\bin\install.bat /y
copy @RootDirectory\bin\DotNet4.0\uinstall.bat @RootDirectory\appserver\bin\uinstall.bat /y
copy @RootDirectory\bin\DotNet4.0\System.Data.SQLite.DLL @RootDirectory\appserver\bin\System.Data.SQLite.DLL /y
copy @RootDirectory\bin\DotNet4.0\System.Workflow.Activities.dll @RootDirectory\appserver\bin\System.Workflow.Activities.dll /y
copy @RootDirectory\bin\DotNet4.0\System.Workflow.ComponentModel.dll @RootDirectory\appserver\bin\System.Workflow.ComponentModel.dll /y
copy @RootDirectory\bin\DotNet4.0\System.Workflow.Runtime.dll @RootDirectory\appserver\bin\System.Workflow.Runtime.dll /y
copy @RootDirectory\bin\DotNet4.0\WF.Demo.DAL.dll @RootDirectory\appserver\bin\WF.Demo.DAL.dll /y

@rem 复制到ActiveXForm.Web\bin
copy @RootDirectory\bin\DotNet4.0\EAS.MicroKernel.dll @RootDirectory\ActiveXForm.Web\bin\EAS.MicroKernel.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.LuaScript.dll @RootDirectory\ActiveXForm.Web\bin\EAS.LuaScript.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Metadata.dll @RootDirectory\ActiveXForm.Web\bin\EAS.Metadata.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Data.dll @RootDirectory\ActiveXForm.Web\bin\EAS.Data.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Distributed.dll @RootDirectory\ActiveXForm.Web\bin\EAS.Distributed.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Explorer.BLL.Contracts.dll @RootDirectory\ActiveXForm.Web\bin\EAS.Explorer.BLL.Contracts.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Explorer.dll @RootDirectory\ActiveXForm.Web\bin\EAS.Explorer.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Explorer.Entities.dll @RootDirectory\ActiveXForm.Web\bin\EAS.Explorer.Entities.dll /y
copy @RootDirectory\bin\DotNet4.0\EAS.Explorer.Web.dll @RootDirectory\ActiveXForm.Web\bin\EAS.Explorer.Web.dll /y

@rem DrugShop文件部署
copy @RootDirectory\bin\DotNet4.0\DrugShop.Entities.dll @RootDirectory\appserver\xclient\files\DrugShop.Entities.dll /y
copy @RootDirectory\bin\DotNet4.0\DrugShop.BLL.Contracts.dll @RootDirectory\appserver\xclient\files\DrugShop.BLL.Contracts.dll /y
copy @RootDirectory\bin\DotNet4.0\DrugShop.Res.dll @RootDirectory\appserver\xclient\files\DrugShop.Res.dll /y
copy @RootDirectory\bin\DotNet4.0\DrugShop.Main.exe @RootDirectory\appserver\xclient\files\DrugShop.Main.exe /y
copy @RootDirectory\bin\DotNet4.0\DrugShop.Main.exe.config @RootDirectory\appserver\xclient\files\DrugShop.Main.exe.config /y

@rem 复制到SOA服务Bin目录
copy @RootDirectory\bin\DotNet4.0\DrugShop.Entities.dll @RootDirectory\appserver\bin\DrugShop.Entities.dll /y
copy @RootDirectory\bin\DotNet4.0\DrugShop.BLL.Contracts.dll @RootDirectory\appserver\bin\DrugShop.BLL.Contracts.dll /y
copy @RootDirectory\bin\DotNet4.0\DrugShop.BLL.Host.dll @RootDirectory\appserver\bin\DrugShop.BLL.Host.dll /y

pause