//------------------------------------------------------------------------------
//     AgileEAS.NET应用开发平台，是基于敏捷并行开发思想以及.NET构件技术而开发的一个应用系统快速开发平台，用于帮助中小软件企业
//建立一条适合快速变化的开发团队，以达到节省开发成本、缩短开发时间，快速适应市场变化的目的。
//     AgileEAS.NET应用开发平台包含基础类库、资源管理平台、运行容器、开发辅助工具等四大部分，资源管理平台为敏捷并行开发提供了
//设计、实现、测试等开发过程的并行，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子
//功能模块按照业务功能组织成单独的程序集文件，各子系统开发完成后，由AgileEAS.NET资源管理平台进行统一的集成部署。
//
//     AgileEAS.NET应用开发平台是一套免费的快速开发工具，可以不受限制的用于各种商业开发之中，开发人员可以参考官方网站和博客园
//等专业网站获取公开的技术资料，也可以向AgileEAS.NET官方团队请求技术支持。
//
// 官方网站：http://www.smarteas.net
// 团队网站：http://www.agilelab.cn
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由AgileEAS.NET数据模型设计工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using EAS.Data.Access;
using EAS.Data.ORM;
using System.Runtime.Serialization;
using System.Data;

namespace DrugShop.Entities
{
   /// <summary>
   /// 实体对象 Account(系统账户)。
   /// </summary>
   [Serializable()]
   [Table("EAS_ACCOUNTS"),Index]
   partial class Account: DataEntity<Account>
   {
       public Account()
       {
       }
       
       protected Account(SerializationInfo info, StreamingContext context)
           : base(info, context)
       {
       }
       
       #region O/R映射成员

       /// <summary>
       /// 登录ID 。
       /// </summary>
       [Column("LOGINID","登录ID"),PrimaryKey]
       public string LoginID
       {
           get
           {
               return this.GetValue<string> ("LOGINID");
           }
           set
           {
               this["LOGINID"] = value;
           }
       }

       /// <summary>
       /// 账户分类 。
       /// </summary>
       [Column("CATEGORY","账户分类")]
       public string Category
       {
           get
           {
               return this.GetValue<string> ("CATEGORY");
           }
           set
           {
               this["CATEGORY"] = value;
           }
       }

       /// <summary>
       /// 账户名称 。
       /// </summary>
       [Column("NAME","账户名称")]
       public string Name
       {
           get
           {
               return this.GetValue<string> ("NAME");
           }
           set
           {
               this["NAME"] = value;
           }
       }

       /// <summary>
       /// 密码 。
       /// </summary>
       [Column("PASSWORD","密码",DbType.Binary)]
       public byte[] Password
       {
           get
           {
               return this.GetValue<byte[]> ("PASSWORD");
           }
           set
           {
               this["PASSWORD"] = value;
           }
       }

       /// <summary>
       /// 属性信息 。
       /// </summary>
       [Column("ATTRIBUTES","属性信息")]
       public int Attributes
       {
           get
           {
               return this.GetValue<int> ("ATTRIBUTES");
           }
           set
           {
               this["ATTRIBUTES"] = value;
           }
       }

       /// <summary>
       /// 登录计数 。
       /// </summary>
       [Column("LOGINCOUNT","登录计数")]
       public long LoginCount
       {
           get
           {
               return this.GetValue<long> ("LOGINCOUNT");
           }
           set
           {
               this["LOGINCOUNT"] = value;
           }
       }

       /// <summary>
       /// 账户说明 。
       /// </summary>
       [Column("DESCRIPTION","账户说明")]
       public string Description
       {
           get
           {
               return this.GetValue<string> ("DESCRIPTION");
           }
           set
           {
               this["DESCRIPTION"] = value;
           }
       }

       /// <summary>
       /// 原型信息 。
       /// </summary>
       [Column("ORIGINALID", "原型信息")]
       public string OriginalID
       {
           get
           {
               return this.GetValue<string>("ORIGINALID");
           }
           set
           {
               this["ORIGINALID"] = value;
           }
       }

       /// <summary>
       /// 证书信息 。
       /// </summary>
       [Column("CERTIFICATE","证书信息")]
       public string Certificate
       {
           get
           {
               return this.GetValue<string> ("CERTIFICATE");
           }
           set
           {
               this["CERTIFICATE"] = value;
           }
       }
       
       #endregion
   }
}
